[tool.ruff]
line-length = 90

[tool.ruff.lint]
pydocstyle.convention = "google"
fixable = ["ALL"]
ignore = ["ANN002", "ANN003", "ANN101", "DTZ005", "PT001", "F722", "N802", "RET505"]
select = [
    "A",
    "ANN",
    "B",
    "BLE",
    "C4",
    "D",
    "DTZ",
    "E",
    "ERA",
    "F",
    "FLY",
    "I",
    "ICN",
    "N",
    "NPY",
    "PD",
    "PIE",
    "PT",
    "Q",
    "PLC",
    "PLE",
    "PLW",
    "PTH",
    "RET",
    "SIM",
    "SLF",
    "T20",
    "TD",
    "TID",
    "UP",
    "W",
    "YTT",
]

[project]
name = "particlesys"
version = "0.1.0"
description = "Particle physics simulation"
dependencies = [
    "pyglet",
    "numpy",
    "loguru",
    "pandas",
    "ruff",
    "pre-commit",
]

[tool.setuptools]
py-modules = []